version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:1.85.4
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Configuração do banco
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres_password
      # Pasta para custom nodes
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    depends_on:
      - postgres

volumes:
  postgres_data:
  n8n_data:
